sugarcube-2:
  macros:
    PC:
      name: PC
      description: |-
        Gets the first name from the variable $player.name and wraps it in a player name specific class.

        Usage:
          ```
          The PC's first name is <<PC>>
          ```
    changePCPersonality:
      name: changePCPersonality
      description: |-
        This widget will be used to increment or decrement the PC's personality as well as also increasing and decreasing other personality values depending on some situations.

        Usage:
          ```
          <<changePCPersonality "personality" value>>

          Where "personality" is the required personality trait to change found in $player.personality and "value" is the number to increase or reduce it by.

          e.g
          <<changePCPersonality "caring" 2>>
          ```
      parameters:
        - text &+ number
    changePCRelationship:
      name: changePCRelationship
      description: |-
        This widget is used to change the relationship value between the player and another character. If the relationship does not exist, it automatically adds it.

        Usage:
          ```
          <<changePCRelationship "character" value>>

          Where "character" is the required character's relationship value to change found in $player.relationships and "value" is the number to increase or reduce it by.

          e.g
          <<changePCRelationship "Fertilo" 7>>
          ```
      parameters:
        - text &+ number
    updatePlayerStats:
      name: updatePlayerStats
      description: |-
        Updates all the player stats at once.

        Usage:
          ```
          <<updatePlayerStats>>
          ```
