#!/bin/bash

transpiledJsDir="src/scripts/built_js"
compiledCssDir="src/styles/built_css"

# Remove previously compiled files so duplicated / unnecessary code is gone
if [ -d "$transpiledJsDir" ]; then
  echo "Transpiled JS Directory found. Deleting..."
  rm -rf "$transpiledJsDir"
  echo "Directory deleted. Proceeding to next step..."
else
  echo "Transpiled JS Directory not found. Proceeding to next step..."
fi

if [ -d "$compiledCssDir" ]; then
  echo "Transpiled CSS Directory found. Deleting..."
  rm -rf "$compiledCssDir"
  echo "Directory deleted. Proceeding to next step..."
else
  echo "Transpiled CSS Directory not found. Proceeding to next step..."
fi

buildMode=${1:-" "}

# Compile SCSS and TypeScript files then call the build script and then run tweego
sass src/styles/scss:"$compiledCssDir" --no-source-map --style=compressed && echo "CSS files rebuilt" && tsc --target es2019 --rootDir src/scripts/ts --outDir "$transpiledJsDir" && echo "JS files rebuilt" && node build.js && tweego -o dist/index.html -m src/modules/ --head="src/head-content.html" project "$buildMode"
