// TODO: Put all the story passages here
export const enum StoryPassageName {
	GAME_START = "GameStart",
	DEBUG_SANDBOX = "DebugSandbox",
	PLAYER_HOUSE = "Your House",
	PROLOGUE_BEGINNING = "Prologue_Beginning",
	PROLOGUE_WAKE_UP_AND_BRUSH_TEETH = "Prologue_WakeUpAndBrushTeeth",
	PROLOGUE_DRESSED_AND_ENTERING_BUS = "Prologue_DressedAndEnteringBus",
	PROLOGUE_BUS_DREAM_0 = "Prologue_BusDream#0",
	PROLOGUE_BUS_DREAM_1 = "Prologue_BusDream#1",
	PROLOGUE_BUS_DREAM_2 = "Prologue_BusDream#2",
	PROLOGUE_BUS_DREAM_3 = "Prologue_BusDream#3",
	PROLOGUE_ARRIVED_AT_FERTILO_INC = "Prologue_ArrivedAtFertiloInc",
	PROLOGUE_ARRIVED_AT_FERTILO_INC_1 = "Prologue_ArrivedAtFertiloInc_1",
	PROLOGUE_CHARACTER_CREATION_TALK_TO_RECEPTIONIST = "FertiloInc_CharacterCreation_TalkToReceptionist",
	PROLOGUE_CHARACTER_CREATION = "FertiloInc_CharacterCreation",
	PROLOGUE_CHARACTER_CREATION_DONE_WITH_MEASUREMENTS = "FertiloInc_CharacterCreation_DoneWithMeasurements",
	PROLOGUE_MEET_THE_DOCTOR = "FertiloInc_Prologue_MeetTheDoctor",
	PROLOGUE_INFO_DUMP = "FertiloInc_Prologue_InfoDump",
	PROLOGUE_INFO_DUMP_1 = "FertiloInc_Prologue_InfoDump1",
	PROLOGUE_MEET_MARIA = "FertiloInc_Prologue_MeetMaria",
	PROLOGUE_GETTING_TO_YOUR_NEW_ROOM = "FertiloInc_Prologue_GettingToYourNewRoom",
	PROLOGUE_GETTING_TO_YOUR_NEW_ROOM_MR_FERT_HAS_TO_LEAVE = "FertiloInc_Prologue_GettingToYourNewRoom_MrFertHasToLeave",
	PROLOGUE_ENTERED_YOUR_ROOM = "FertiloInc_Prologue_EnteredYourRoom",
	PROLOGUE_TUTORIAL_FOR_YOUR_ROOM = "FertiloInc_Prologue_TutorialForYourRoom",

	PLAYER_BATHROOM = "Player_Bathroom",
	PLAYER_BEDROOM = "Player_Bedroom",
	PLAYER_KITCHEN = "Player_Kitchen",
	PLAYER_LIVING_ROOM = "Player_LivingRoom",
	PLAYER_PORCH = "Player_Porch",
}
