// TODO: Put all the story passages here
export const enum StoryPassageName {
	GAME_START = "GameStart",
	DEBUG_SANDBOX = "DebugSandbox",
	PLAYER_HOUSE = "Your House",
	PROLOGUE_BEGINNING = "Prologue_Beginning",
	PROLOGUE_WAKE_UP_AND_BRUSH_TEETH = "Prologue_WakeUpAndBrushTeeth",
	PROLOGUE_DRESSED_AND_ENTERING_BUS = "Prologue_DressedAndEnteringBus",
	PROLOGUE_BUS_DREAM_0 = "Prologue_BusDream#0",
	PROLOGUE_BUS_DREAM_1 = "Prologue_BusDream#1",
	PROLOGUE_BUS_DREAM_2 = "Prologue_BusDream#2",
	PROLOGUE_BUS_DREAM_3 = "Prologue_BusDream#3",
	PROLOGUE_ARRIVED_AT_FERTILO_INC = "Prologue_ArrivedAtFertiloInc",
	PROLOGUE_ARRIVED_AT_FERTILO_INC_1 = "Prologue_ArrivedAtFertiloInc_1",
	PROLOGUE_CHARACTER_CREATION_TALK_TO_RECEPTIONIST = "FertiloInc_CharacterCreation_TalkToReceptionist",
	PROLOGUE_CHARACTER_CREATION = "FertiloInc_CharacterCreation",
	PROLOGUE_CHARACTER_CREATION_DONE_WITH_MEASUREMENTS = "FertiloInc_CharacterCreation_DoneWithMeasurements",
	PROLOGUE_MEET_THE_DOCTOR = "FertiloInc_Prologue_MeetTheDoctor",
	PROLOGUE_INFO_DUMP = "FertiloInc_Prologue_InfoDump",
	PROLOGUE_INFO_DUMP_1 = "FertiloInc_Prologue_InfoDump1",
	PROLOGUE_MEET_MARIA = "FertiloInc_Prologue_MeetMaria",
	PROLOGUE_GETTING_TO_YOUR_NEW_ROOM = "FertiloInc_Prologue_GettingToYourNewRoom",
	PROLOGUE_GETTING_TO_YOUR_NEW_ROOM_MR_FERT_HAS_TO_LEAVE = "FertiloInc_Prologue_GettingToYourNewRoom_MrFertHasToLeave",
	PROLOGUE_ENTERED_YOUR_ROOM = "FertiloInc_Prologue_EnteredYourRoom",
	PROLOGUE_TUTORIAL_FOR_YOUR_ROOM = "FertiloInc_Prologue_TutorialForYourRoom",
	PROLOGUE_TUTORIAL_TO_WORK = "FertiloInc_Prologue_TutorialToWork",
}

export const enum NorthHirthefordPassageName {
	FERTILO_INC_CONSULTATION = "Fertilo_Inc_Consultation",
	FERTILO_INC_CORRIDOR = "Fertilo_Inc_Corridor",
	FERTILO_INC_HALLWAY = "Fertilo_Inc_Hallway",
	FERTILO_INC_LAB = "Fertilo_Inc_Lab",
	FERTILO_INC_CLOSET = "Fertilo_Inc_Closet",
	FERTILO_INC_OFFICE = "Fertilo_Inc_Office",
	FERTILO_INC_PHARMACY = "Fertilo_Inc_Pharmacy",
	FERTILO_INC_PORCH = "Fertilo_Inc_Porch",
	FERTILO_INC_RECEPTION = "Fertilo_Inc_Reception",
	FERTILO_INC_OFFICE_CEO = "Fertilo_Inc_Office_Ceo",
	FERTILO_INC_PLAYER_ROOM = "Fertilo_Inc_Player_Room",
}

export const enum WestHirthefordPassageName {
	BACKUP = "Backup",
	PLAYER_OLD_BATHROOM = "Player_Old_Bathroom",
	PLAYER_OLD_BEDROOM = "Player_Old_Bedroom",
	PLAYER_OLD_KITCHEN = "Player_Old_Kitchen",
	PLAYER_OLD_PORCH = "Player_Old_Porch",
	PLAYER_OLD_ROOM = "Player_Old_Room",
}
