sugarcube-2:
  macros:
    updateGameTime:
      name: updateGameTime
      description: |-
        <<updateGameTime "nextDay" 7 30>> to skip to 7:30 am on the next day
        
        <<updateGameTime 21 15 21>> to skip to 3:21 pm 21 days forwards

        Easy enough?
      parameters:
        - (text|number) &+ number &+ number