sugarcube-2:
  macros:
    impregnate:
      name: impregnate
      description: |-
        ```
        <<impregnate 70 10 $player.womb>> to try and fertilize the player using a source with a high virility of 70% and a slight boost of 10 (out of 30)

        <<impregnate 62 21 $player.womb 3>> will fertilize the player using a source with a decent virility of 62% and a high boost of 21 (out of 30). However, since the number of fetuses to spawn, `3`, was supplied, pregnancy with triplets is guaranteed
        ```

        Easy enough?
      parameters:
        - number &+ number &+ receiver |+ number
    updatePregnancy:
      name: updatePregnancy
      description: |-
        ```
        <<updatePregnancy $player.womb>> will update the growth of the fetuses in the womb
        ```

        Easy enough?
      parameters:
        - receiver
    isPregBellySizeInRange:
      name: isPregBellySizeInRange
      description: |-
        ```
        <<isPregBellySizeInRange $player.womb _varToStoreResult "EARLY_PREGNANCY" "LATE_PREGNANCY">> will check if the player's womb's size ranges between BellyState.EARLY_PREGNANCY and BellyState.LATE_PREGNANCY (you can find the appropriate string values to use in "BellyState" in the preg declaration).
        The last argument is optional.

        To check if the belly size is below a specific value alone, set the 3rd argument to "MIN"
        ```

        Easy enough?
      parameters:
        - receiver &+ string &+ string |+ string
